@baseUrl = http://localhost:5555
@access_token = {{authenticate.response.body.access_token}}

# @name createAccount
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe+3@example.com",
  "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "john.doe+2@example.com",
  "password": "123456"
}

###

# @name createQuestion
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "title": "New question 4",
  "content": "Content of the question"
}

###

# @name fetchRecentQuestions
GET {{baseUrl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{access_token}}
